### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by dsturge01** [MalwareSupportGroup/PolyDrop#1]
// compiled with no changes to source code

//command:
polydrop.exe -s dart -t sh -l 192.168.45.232 -p 4434 -u https://gist.github.com/byt3bl33d3r/1da9d0725a5f1bb8502fce5eda8faa42 -x windows

// Error:
thread 'main' panicked at src\builder\arguments\mod.rs:129:37:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff66425883d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff66425883d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff66425883d - std::sys_common::backtrace::_print_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ff66425883d - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff6642724e9 - core::fmt::rt::Argument::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\rt.rs:165
   5:     0x7ff6642724e9 - core::fmt::write
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\mod.rs:1168
   6:     0x7ff664254ea1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\io\mod.rs:1835
   7:     0x7ff664258616 - std::sys_common::backtrace::print
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff66425a508 - std::panicking::default_hook::closure$1
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:271
   9:     0x7ff66425a1b6 - std::panicking::default_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:298
  10:     0x7ff66425aa38 - std::panicking::rust_panic_with_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:795
  11:     0x7ff66425a8b9 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:656
  12:     0x7ff664258f2f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:171
  13:     0x7ff66425a5a8 - std::panicking::begin_panic_handler
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:652
  14:     0x7ff66427c544 - core::panicking::panic_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:72
  15:     0x7ff66427c60d - core::panicking::panic
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:146
  16:     0x7ff66427c4ae - core::option::unwrap_failed
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\option.rs:1985
  17:     0x7ff663c5f0c1 - enum2$<core::option::Option<ref$<str$> > >::unwrap
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\option.rs:935
  18:     0x7ff663c5f0c1 - polydrop::builder::arguments::getargs
                               at C:\Users\david\Downloads\PolyDrop-main\PolyDrop-main\src\builder\arguments\mod.rs:129
  19:     0x7ff663c8f027 - polydrop::main::async_block$0
                               at C:\Users\david\Downloads\PolyDrop-main\PolyDrop-main\src\main.rs:51
  20:     0x7ff663c7f6bf - core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\future\future.rs:123
  21:     0x7ff663c6ebb9 - tokio::runtime::park::impl$4::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\park.rs:281
  22:     0x7ff663c6e674 - tokio::runtime::coop::with_budget
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\coop.rs:107
  23:     0x7ff663c6e674 - tokio::runtime::coop::budget
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\coop.rs:73
  24:     0x7ff663c6e674 - tokio::runtime::park::CachedParkThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\park.rs:281
  25:     0x7ff663bf6b1a - tokio::runtime::context::blocking::BlockingRegionGuard::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\context\blocking.rs:66
  26:     0x7ff663c731b0 - tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\scheduler\multi_thread\mod.rs:87
  27:     0x7ff663c6140e - tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >,tuple$<> >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\context\runtime.rs:65
  28:     0x7ff663c73181 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\scheduler\multi_thread\mod.rs:86
  29:     0x7ff663c1f7d1 - tokio::runtime::runtime::Runtime::block_on_inner<core::pin::Pin<alloc::boxed::Box<enum2$<polydrop::main::async_block_env$0>,alloc::alloc::Global> > >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\runtime.rs:363
  30:     0x7ff663c1f8eb - tokio::runtime::runtime::Runtime::block_on<enum2$<polydrop::main::async_block_env$0> >
                               at C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.3\src\runtime\runtime.rs:333
  31:     0x7ff663c00930 - polydrop::main
                               at C:\Users\david\Downloads\PolyDrop-main\PolyDrop-main\src\main.rs:66
  32:     0x7ff663bd863b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\ops\function.rs:250
  33:     0x7ff663bf3c7e - core::hint::black_box
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\hint.rs:338
  34:     0x7ff663bf3c7e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\sys_common\backtrace.rs:155
  35:     0x7ff663bf43d1 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:159
  36:     0x7ff66424fbbe - std::rt::lang_start_internal
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\rt.rs:141
  37:     0x7ff663bf43aa - std::rt::lang_start<tuple$<> >
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:158
  38:     0x7ff663c00a09 - main
  39:     0x7ff66427a030 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  40:     0x7ff66427a030 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  41:     0x7ffbe1dc7374 - BaseThreadInitThunk
  42:     0x7ffbe275cc91 - RtlUserThreadStart

**Comment by tztao** [comment]
you are missing `-o` flag. i run ur cmd with `-o ok`:
```
- BYOSI (Bring-Your-Own-Script-Interpreter) Rapid Payload Deployment
OS: windows
Payload Type: sh
Output: ok

LHOST: 192.168.45.232
LPORT: 4434
URL: https://gist.github.com/byt3bl33d3r/1da9d0725a5f1bb8502fce5eda8faa42

All: false

Mapping the platform real quick...

Toolchain is empty, selecting the default download URL.
https://storage.googleapis.com/dart-archive/channels/stable/release/3.3.4/sdk/dartsdk-windows-x64-release.zip
```
